rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "10002:28015"
   - "10003:29015"
server:
  build: .
  ports:
   - "80:80"
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: production
    PORT: 80
  volumes:
    - ./:/app
  command: 'npm start'
