rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "10201:8080"
   - "10203:28015"
   - "10203:29015"
server:
  build: .
  ports:
   - "10200:10200"
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: production
    PORT: 10200
  volumes:
    - ./:/app
  command: 'npm start'
